apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-nginx
  name: test-nginx
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: test-nginx
  type: LoadBalancer
status:
  loadBalancer: {}
